INSERT INTO Usuario(ID,User,SENHA,NOME) VALUES(1,'admin','admin','admin')

INSERT INTO Produto(id,Nome_Produto, Valor_Produto, Descricao_Produto, Quantidade_Produto,Vendedor_Id) VALUES(1,'BANANA', 2, 'BANANINHA', 5,1)
INSERT INTO Produto(id,Nome_Produto, Valor_Produto, Descricao_Produto, Quantidade_Produto,Vendedor_Id) VALUES(2,'MAÇA', 2, 'MACAZINHA', 5,1)
INSERT INTO Produto(id,Nome_Produto, Valor_Produto, Descricao_Produto, Quantidade_Produto,Vendedor_Id) VALUES(3,'ABACATE', 2, 'ABACATE', 5,1)
INSERT INTO Produto(id,Nome_Produto, Valor_Produto, Descricao_Produto, Quantidade_Produto,Vendedor_Id) VALUES(4,'MELÃO', 2, 'MELÃOZINHO', 5,1)
INSERT INTO Produto(id,Nome_Produto, Valor_Produto, Descricao_Produto, Quantidade_Produto,Vendedor_Id) VALUES(5,'MELANCIA', 2, 'MALANCIAZINHA', 5,1)
INSERT INTO Produto(id,Nome_Produto, Valor_Produto, Descricao_Produto, Quantidade_Produto,Vendedor_Id) VALUES(6,'LARANJA', 2, 'LARANJINHA', 5,1)
INSERT INTO Produto(id,Nome_Produto, Valor_Produto, Descricao_Produto, Quantidade_Produto,Vendedor_Id) VALUES(7,'UVAZINHA', 2, 'UVAZINHA', 5,1)
INSERT INTO Produto(id,Nome_Produto, Valor_Produto, Descricao_Produto, Quantidade_Produto,Vendedor_Id) VALUES(8,'PERA', 2, 'PERAZINHA', 5,1)
INSERT INTO Produto(id,Nome_Produto, Valor_Produto, Descricao_Produto, Quantidade_Produto,Vendedor_Id) VALUES(9,'LARANJA', 2, 'LARANJINHA', 5,1)
INSERT INTO Produto(id,Nome_Produto, Valor_Produto, Descricao_Produto, Quantidade_Produto,Vendedor_Id) VALUES(10,'MORANGO', 2, 'MORAGUINHO', 5,1)
INSERT INTO Produto(id,Nome_Produto, Valor_Produto, Descricao_Produto, Quantidade_Produto,Vendedor_Id) VALUES(11,'ABACAXI', 2, 'ABACAXIZINHO', 5,1)
INSERT INTO Produto(id,Nome_Produto, Valor_Produto, Descricao_Produto, Quantidade_Produto,Vendedor_Id) VALUES(12,'AMEIXA', 2, 'AMEIXINHA', 5,1)
INSERT INTO Produto(id,Nome_Produto, Valor_Produto, Descricao_Produto, Quantidade_Produto,Vendedor_Id) VALUES(13,'KIWI', 2, 'KIWIZINHO', 5,1)
